name: partner
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+10

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^2.5.0
  cupertino_icons: ^0.1.2
  dio: ^3.0.10
  extended_text: ^4.0.0
  extended_image_library: ^0.3.1
  extended_image: ^1.5.0
  extended_sliver: ^1.0.1
  fish_redux: ^0.3.1
  flutter_svg: ^0.19.0
  flutter_svprogresshud: 0.0.4
  flutter_swiper: ^1.1.6
  http_client_helper: any
  image: ^2.1.4
  image_editor: ^0.1.2
  intl: any
  isolate: ^2.0.2
  js: ^0.6.1+1
  loading_more_list: ^3.0.0
  like_button: any
  oktoast: ^2.1.4
  photo_manager: 0.5.7
  photo_view: ^0.10.3
  pull_to_refresh_notification: any
  shared_preferences: ^0.5.12+4
  url_launcher: 5.3.0
  wechat_assets_picker: ^4.1.0+4


  flutter_staggered_grid_view: ^0.3.2
  gesture_zoom_box: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  ff_annotation_route: ^4.0.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/home/mine/
    - images/splash/
    - images/tab_bar/
    - images/widget/list/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
